# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf162b42fe723a03ef45a13d6e850c3198a29711d7061f8ed61f70e278e88a8b284345c624e69af67e6a0026f9e0314b56537cef5b8b99b82b45418e03210ac

test:
  secret_key_base: 4aea60f6b7cd0c1e0138484f60b550e612d7caaf8a795f8f70acbf2bc3c43766bd39cf8d75921c655ee691623f21649ca5a4b86479c2d6dec74d1d27c966356b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
